language: python
python: 3.7
os: linux
dist: bionic
arch: arm64

before_install:
  - pip list
  - pwd
  - ls -al ~
  - ls -al ~/.cache/pip/wheels

install:
  - python -m pip wheel matplotlib -w ~/dest
script:
  - ls -al ~/dest
  - ls -al ~/.cache/pip/wheels
  - pip list
