language: python

os: linux
dist: bionic
arch: arm64

before_install:
  - pip list
  - pwd
  - echo $HOME
  - ls -al ~/.cache/pip/wheels

install:
  - python -m pip wheel matplotlib -w ~/dest
script:
  - ls -al ~/dest
  - ls -al ~/.cache/pip/wheels
  - pip list
