sudo: true
language: python
python: 3.7
os: linux
dist: bionic
arch: arm64

before_install:
  - python --version
  - pip --version
  - pip list
  - python -m pip install -U pip wheel setuptools
  - pip list
  - whoami
  - ls -al /home/travis/.cache/pip/wheels
  - python -m pip wheel cppy>=1.1.0 -w ./dist
install:
  - python -m pip wheel matplotlib -w ./dist
script:
  - ls -al ./dist
  - pip list
