sudo: false
language: python
python: 3.7
os: linux
dist: bionic
arch: arm64

before_install:
  - python --version
  - pip --version
  - pip list
  - python -m pip install -U pip wheel setuptools
  - pip list
  - whoami
  - docker run --rm python bash -c "pip list; pip wheel matplotlib -w ./dist; ls -al ./dist"


install:

script:
  - ls -al .
  - pip list
