sudo: true
language: python
python: 3.7
os: linux
dist: bionic
arch: arm64

before_install:
  - python --version
  - pip --version
  - pip list
  - pip install -U pip wheel setuptools
  - pip list
install:
  - pip install matplotlib
script:
  - pip list
