jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.7', '3.8' ]
    name: Python ${{ matrix.python-version }} package compiler
    steps:
      - name: Check out package source code
      	uses: actions/checkout@v2
        with:
        	repository: matplotlib/matplotlib
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
      	run: sudo apt-get build-dep python-matplotlib
      - name: Build package
      	run: python -m pip install .
      - name: Checck the results
      	run: ls -l ./dist
        
